baseURL = 'https://projects.pgersl.xyz/'
title = '/Projects'
languageCode = "en-us"
defaultContentLanguage = "en"
uglyURLs = "false"
enableEmoji = "true"
[params]
    description = "Subdomain for personal and school projects and testing"
[menu]
    [[menu.main]]
        identifier = "ads"
        name = "ADS"
        url = "/ads"
        weight = "1"
[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = "true"
    [markup.tableOfContents]
        ordered = true
        startLevel = 0
        endLevel = 3